version: 2.0
version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.6
        working_directory: ~/spotify-public-proxy
        steps:
            - checkout
            - run:
                name: Install Dependencies
                command: sudo pip install -r requirements.txt
            - run:
                name: Install test dependencies
                command: sudo pip install nose2 flake8 aiohttp
            - run:
                name: Run Tests
                command: nose2
            - run:
                name: Lint
                command: flake8 src --ignore=E128,E501 && flake8 tests --ignore=E128,E501

