version: 2
jobs:
    build:
        docker:
            - image: circleci/node:8.10
        working_directory: ~/spotify-public-proxy
        steps:
            - checkout
            - run: npm install
            - run: npm run build
