version: 2.0
version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.6
        working_directory: ~/spotify-public-proxy
        steps:
            - checkout
            - run:
                name: Install Dependencies
                command: pip install -r requirements.txt
            - run:
                name: Install test dependencies
                command: pip install nose2
            - run:
                name: Run Tests
                command: nose2

