name: Build

on: [push]

env:
  SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
  SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build . --tag ${GITHUB_REPOSITORY,,}

      - name: Show image info
        run: docker images

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v1
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: pip install -r dev-requirements.txt
    - name: Run tests
      run: ./scripts/test.sh

  deploy:
    needs:
      - build
      - docker
    if: github.ref_name == 'master'
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push containers
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.ref == 'refs/heads/master' }}
          platforms: linux/arm,linux/amd64,linux/arm64/v8
          tags: |
            ghcr.io/realorangeone/spotify-public-proxy:latest

